const DISCORD_APP_ID = 'DISCORD_APP_ID';
const DISCORD_BOT_TOKEN = 'DISCORD_BOT_TOKEN';
const DISCORD_PUBLIC_KEY = 'DISCORD_PUBLIC_KEY';
const DISCORD_CLIENT_SECRET = 'DISCORD_CLIENT_SECRET';
const DISCORD_CALLBACK_URL = 'DISCORD_CALLBACK_URL';

export {
  DISCORD_APP_ID,
  DISCORD_BOT_TOKEN,
  DISCORD_PUBLIC_KEY,
  DISCORD_CLIENT_SECRET,
  DISCORD_CALLBACK_URL,
};
